### ISSUE TITLE
 Cannot run program "infocmp": CreateProcess error=2, The system cannot find the file specified

### ISSUE THREAD

**Issue by Badetuch** [ctongfei/progressbar#57]
When I want to start my programm, I get this long error
`java.io.IOException: Cannot run program "infocmp": CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at org.jline.utils.InfoCmp.getInfoCmp(InfoCmp.java:547)
	at org.jline.terminal.impl.AbstractTerminal.parseInfoCmp(AbstractTerminal.java:187)
	at org.jline.terminal.impl.DumbTerminal.<init>(DumbTerminal.java:88)
	at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:401)
	at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:259)
	at me.tongfei.progressbar.ProgressThread.<init>(ProgressThread.java:56)
	at me.tongfei.progressbar.ProgressBar.<init>(ProgressBar.java:91)
	at me.tongfei.progressbar.ProgressBar.<init>(ProgressBar.java:39)
	at de.badespeak.teamspeakbot2.main.Load.main(Load.java:69)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:420)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:151)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 10 more`

My Code:
https://hastebin.com/uconocixub

**Comment by ctongfei** [comment]
Is this the same problem as #55 ? Please report your OS and terminal environment.

**Comment by ctongfei** [comment]
Also, try using `ProgressBarStyle.ASCII` instead of the default colorful unicode style.

**Comment by ctongfei** [comment]
As of now this seems to be #55  -- so I'm closing this and favor the discussions go to #55 . Thanks for reporting this!
