### ISSUE TITLE
IOError occurs randomly

### ISSUE THREAD

**Issue by aguedeney** [ctongfei/progressbar#83]
I don't get these very often, but when I do it seems very difficult to capture in a try/catch. It usually occurs if the file is small or the time span is short. Any ideas?

2% [>                       ]  13942/511096 (0:00:00 / 0:00:00) 0.49MB
Exception in thread "me.tongfei.progressbar.ProgressBar" java.io.IOError: java.io.InterruptedIOException: Command interrupted
	at org.jline.terminal.impl.AbstractPosixTerminal.getSize(Unknown Source)
	at org.jline.terminal.Terminal.getWidth(Unknown Source)
	at me.tongfei.progressbar.Util.getTerminalWidth(Unknown Source)
	at me.tongfei.progressbar.ConsoleProgressBarConsumer.getMaxProgressLength(Unknown Source)
	at me.tongfei.progressbar.ProgressThread.refresh(Unknown Source)
	at me.tongfei.progressbar.ProgressThread.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.InterruptedIOException: Command interrupted
	at org.jline.utils.ExecHelper.exec(Unknown Source)
	at org.jline.terminal.impl.ExecPty.doGetConfig(Unknown Source)
	at org.jline.terminal.impl.ExecPty.getSize(Unknown Source)
	... 7 more
Caused by: java.lang.InterruptedException
	at java.base/java.lang.Object.wait(Native Method)
	at java.base/java.lang.Object.wait(Unknown Source)
	at java.base/java.lang.ProcessImpl.waitFor(Unknown Source)
	at org.jline.utils.ExecHelper.waitAndCapture(Unknown Source)
	... 10 more

**Comment by ctongfei** [comment]
I'm not sure of why this happens: but since the error is from `AbstractPosixTerminal.getSize`, did you move or resize your terminal window very frequently? I'm trying to understand the underlying problem here.

**Comment by aguedeney** [comment]
I'm using a docker container, specifically Alpine Linux 3.12.  9 out of 10 times everything works great - no problems.  It's that 1% of the time I get that IOError exception.  The terminal is static: meaning no resizing is occurring.  So, I'd like to present a couple of solutions that would leave nothing to chance that would help resolve this issue.

1. Allow API to maintain a static width regardless of resizing TTY.
2. Do not throw IOError exception instead UnknownSizeException so that developer's can catch the Exception when it is thrown.

At the moment, I am not able to catch the IOError exception and handle it for the 1% of the time this occurs.  I've tried to catch IOError and the try-catch block is simply ignored - irritating.

Overall, this progress indicator works very well and I've had no problems with it everywhere I use it.

**Comment by ctongfei** [comment]
Thanks @aguedeney . This would then be linked to #71 : If the builder uses the custom `setWidth`, no calls to `AbstractPosixTerminal.getSize` will be made.

**Comment by ctongfei** [comment]
Closing since there is `setMaxRenderedLength` to maintain a static terminal width regardless of resizing.
